### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by alvin-dennis** [alvin-dennis/Personal-Portfolio-V2#1]
Need contribution for setting up a server for contact form using nodemailer

**Comment by EmaanFarhat** [comment]
@alvin-dennis  Hy I tried to message you on Whatsapp but your number is not on whatsapp
Kindly contact me asap so that i can share my whatsapp number

**Comment by alvin-dennis** [comment]
@EmaanFarhat yeah mention ur number here. I will delete the comment here later

**Comment by EmaanFarhat** [comment]
@alvin-dennis +923021011525

**Comment by alvin-dennis** [comment]
I have sent a hi @EmaanFarhat
