### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by EmaanFarhat** [alvin-dennis/Personal-Portfolio-V2#3]
Hy Alvin
So You are using Contact form how are you submitting the form?
![image](https://github.com/alvin-dennis/Personal-Portfolio-V2/assets/113349013/fa354bb1-93aa-43b8-aef6-ad3c969749e3)

**Comment by alvin-dennis** [comment]
@EmaanFarhat hi the owner of this code uses the backend for the email and service status to work

**Comment by EmaanFarhat** [comment]
I want the contact form up and running

**Comment by alvin-dennis** [comment]
@EmaanFarhat I need to code a backend for that

**Comment by EmaanFarhat** [comment]
@alvin-dennis Can you help me with that?

**Comment by alvin-dennis** [comment]
@EmaanFarhat I also have no experience in nodemailer. I am sort of a frontend guy. No experience in backend. This portfolio doesn't have a backend code

**Comment by EmaanFarhat** [comment]
@alvin-dennis No can you help me with contact form?

**Comment by alvin-dennis** [comment]
@EmaanFarhat I have no experience using nodemailer and writing backend. I can try tho. I also need to set up  the contact form for mine too

**Comment by EmaanFarhat** [comment]
@alvin-dennis can you do this asap?

**Comment by EmaanFarhat** [comment]
@alvin-dennis  actually i need that at the end of this month

**Comment by alvin-dennis** [comment]
@EmaanFarhat I am not saying I will complete it but lemme try

**Comment by EmaanFarhat** [comment]
@alvin-dennis 
Ok Please keep me updated

**Comment by alvin-dennis** [comment]
Do u have WhatsApp or something? @EmaanFarhat 
Issues have a lot of chats already 🫠

**Comment by EmaanFarhat** [comment]
Give me your i will message you @alvin-dennis

**Comment by alvin-dennis** [comment]
9747153663

**Comment by EmaanFarhat** [comment]
Ok

**Comment by alvin-dennis** [comment]
9747153663 @EmaanFarhat 
I accidentally deleted

**Comment by EmaanFarhat** [comment]
@alvin-dennis  Ok
